### PR TITLE
v2

### PR DESCRIPTION
**Pull request by charlesrocket**

### CODE REVIEW

**Review by NaH012 — CHANGES_REQUESTED** [review]
The reason we use a domain names for the seeds is we can overload the domain ip lookup with as many ips want. Then if an ip changes nothing breaks as it is a simple api call to update the domain registrar of choice and all cores continue to function without needing a new binary when searching for active nodes.

Also, nice
image

**Comment by charlesrocket** [comment]
@NaH012 Got it

Leet changes ahah 😅

**Review by NaH012 — APPROVED** [review]

**Review by NaH012 — CHANGES_REQUESTED** [review]
The seeds are fixed, but the automated builds are still failing. I've checked the build report on travis ci and it looks like it fails due to subtree checking. I haven't used subtrees before so I don't really know what is going on.

Once the automated builds pass testing then I'll reach out to [other members of the community on reddit](reddit.com/r/defcoin) to have them test the cores to make sure there is no hard fork caused by updating. SImilar to when v1 was pushed. The old core still accepts the blocks from the new core.

**Comment by charlesrocket** [comment]
Guess ill close it then till theres a competent maintainer who can see such PR thro.

**Comment by NaH012** [comment]
I don't have the time to all the work, but if you would be willing to help me update it I can put in a couple of hours a week. The biggest issue is settings to make the cores compatible gets moved around between files a lot from what I've experienced, then we also need to test sending coins between wallets on the new cores and send new blocks to ensure compatibility. If you would also be willing to help debug and put in work I can pull this into a development branch and we can work from there.

Edit: I may not know some stuff now, but I'll learn. I taught my self blockchain by updating this core so it has always been a learning project for me.

**Comment by charlesrocket** [comment]
Looks like the biggest issue so far is removing 4 lines from CI))))) I suggest you dropping CI starting from scratch, rebuilding subtrees, if red flags are too annoying at the moment. Opening dev branch and cherry-picking `v2` might might be a good way to start. Also you don't really need dev branch - theres a snap of source you can get from the tag when you need to compile so no reason for main branch/`STABLE` assuming every release is stable.

**Comment by charlesrocket** [comment]
I polished CI on my fork so maybe you want to move the community there since theres issue tracker. I sent you the write access.

**Comment by NaH012** [comment]
I've activated the issue tracker. I thought it was active when I first launched the new core. Since the community already has links to this repo I think it best to have it remain here. I've pulled your changed to [the v2 branch](https://github.com/NaH012/Defcoin/tree/v2) and given you collaboration permissions.

**Comment by charlesrocket** [comment]
@NaH012 opening issue tracker 2 years after - good job))

**Pull request closed without merging**
